# Nixpacks configuration for Railway
# This helps Railway understand your project structure

[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmds = [
  "npm install --prefix 'Robridge web'",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build --prefix 'Robridge web'"]

[start]
cmd = "node 'Robridge web/server.js'"

